manage my process

diff --git a/processes_and_signals/11-manage_my_process b/processes_and_signals/11-manage_my_process
--- a/processes_and_signals/11-manage_my_process
+++ b/processes_and_signals/11-manage_my_process
@@ -1,5 +1,43 @@
 #!/usr/bin/env bash
 #script that manages manage_my_process script
 
-SCRIPT_PATH=/var/run/my_process.pid
+SCRIPT_PATH=/path/to/my_process.pid
+function start_process() {
+	$SCRIPT_PATH &
+	PID=$!
+	echo $PID > /var/run/my_process.pud
+	echo "manage_my_process started"
+}
 
+function stop_process(){
+	if [ -f "/var/run/my_process.pid" ]; then
+		PID=$(cat /var/run/my_process.pid)
+		"kill $PID"
+		rm /var/run/my_process.pid
+		echo "manage_my_process stopped"
+	else
+		echo "PID file not found. manage_my_process may not be running."
+	fi
+	}
+function restart_process(){
+	stop_process
+	start_process
+	echo "manage_my_process restarted"
+}
+case $1 in 
+	start)
+		start_process
+		;;
+	stop)
+		stop_process
+		;;
+	restart)
+		restart_process
+		;;
+	*)
+		echo "Usage: $0 {start|stop|restart}"
+		exit 1
+		;;
+esac
+
+exit 0
